fix: allow system to generate random port when desired (#319)
JustinBeckwith/linkinator pull request #320
Opened 2021-07-20 17:12 UTC by rrthomas

2021-08-12 17:54 UTC, JustinBeckwith requested changes
Thanks for the PR!  A few questions.

2021-08-12 17:54 UTC, JustinBeckwith commented on build/src/cli.d.ts
> +#!/usr/bin/env node
Not sure how this happened, but we shouldn't check the `build` dir in since it's compiler output.  Mind removing this?

2021-08-12 17:54 UTC, JustinBeckwith commented on src/index.ts
> +        const addr = server.address() as AddressInfo;
So does this mean the underlying web server is going to use it's own logic to grab a random port?

2021-08-16 11:03 UTC, rrthomas commented
I'm sorry, I overlooked the fact that I committed a lot of built files in order to allow using my fork as a dependency in GitLab builds. I am closing this PR and will reopen with a branch that only has my changes.

2021-08-16 11:03 UTC, closed without merging